#pragma config(Hubs,  S1, HTMotor,  HTMotor,  none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     motorD,        tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C1_2,     motorE,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     motorF,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     motorG,        tmotorTetrix, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"

//----------------------------- Initialization ------------------------------

int motorSlow = 1;

int motorSpeedD = 0;
int motorSpeedE = 0;

void initializeRobot() { //Initialize, setting all motors to a speed of 0.
	motor[motorD] = 0;
	motor[motorE] = 0;
	motor[motorF] = 0;
	motor[motorG] = 0;
}

//--------------------  Joystick 1 (Driver) Controls --------------------------

int getJoy1y1() { //Get the left side movement.
	if(joystick.joy1_y1 > 10 || joystick.joy1_y1 < -10) {
		return joystick.joy1_y1 / 3;
	}
	else return 0;
}
int getJoy1y2() {  //Get the right side movement.
	if(joystick.joy1_y2 > 10 || joystick.joy1_y2 < -10) {
		return joystick.joy1_y2 / 3;
	}
	else return 0;
}

int getMotorSlow() { //Returns which speed to go at
  if (joy1Btn(1) == 1) return 1; //fast X Button
  else if (joy1Btn(2) == 1) return 2; //medium A position
  else if (joy1Btn(3) == 1) return 4; //slow B position
  else return 0;
}

void joy1Controls() {
	getJoystickSettings(joystick);
	motorSpeedD = getJoy1y2();
	motorSpeedE = getJoy1y1();
	if(getMotorSlow() != 0)	{
		motorSlow = getMotorSlow();
	}
	if(joy1Btn(8) == 1) {
		motor[motorD] = 10;
		motor[motorE] = 10;
	}
	else if(joy1Btn(7) == 1) {
		motor[motorD] = -10;
		motor[motorE] = -10;
	}
	else if(joy1Btn(5) == 1) {
		motor[motorD] = 17;
		motor[motorE] = -17;
	}
	else if(joy1Btn(6) == 1) {
		motor[motorD] = -17;
		motor[motorE] = 17;
	}
	else {
  	motor[motorD] = motorSpeedD / motorSlow;
  	motor[motorE] = motorSpeedE / motorSlow;
	}
}

// ------------------- Joystick 2 (Gunner) Controls ------------------------

void joy2Controls() {
	if(joy2Btn(1) == 1) {
		motor[motorF] = 75;
	} else if(joy2Btn(3) == 1) {
		motor[motorF] = -75;
	} else {
		motor[motorF] = 0;
	}
	
	if(joy2Btn(2) == 1) {
		motor[motorG] = 75;
	} else if(joy2Btn(4) == 1) {
		motor[motorG] = -75;
	} else {
		motor[motorG] = 0;
	}

}

//--------------------------------- Main --------------------------------

task main() {
    initializeRobot();
    waitForStart();

    while(true) {
	    joy1Controls();
	    joy2Controls();
    }
}
